# Run this file to make a compile_commands.json file in your project root directory


# The compile_commands.json generated by cmake has info for all binaries but not the header files
# Due to that there might be squiggles in ide while  working with some ides


#  https://pypi.org/project/compdb/
#  This script will use compdb to generate compile_commands.json file
#  which will have header information as well

# Running format : python make_compile_commands.py (<build_directory>)?

import sys
import subprocess
try:
    import compdb
except:
    p = subprocess.Popen(['pip', 'install', 'compdb', '--user'])
    p.wait()
    import compdb


def main():
    build = "build"
    if(len(sys.argv) >= 2):
        build = sys.argv[1]
    process = subprocess.Popen(
        ['compdb', '-p', build, 'list'], stdout=subprocess.PIPE)
    text = process.communicate()[0]
    open('compile_commands.json', 'wb').write(text)
    print("Wrote compile_commands.json successfully")


main()
